name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: myapp
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.6.1'

    - name: Install dependencies
      run: npm --prefix 01-url-parser install && npm --prefix 02-api-with-database install

    - name: Wait for Postgres
      run: until pg_isready --host=localhost --port=5432; do echo 'waiting for pg'; sleep 1; done

    - name: Run tests for URL Parser
      run: npm --prefix 01-url-parser test

    - name: Run tests for API
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/myapp
        LOG_LEVEL: info
      run: npm --prefix 02-api-with-database
